# Generated by Django 4.2.4 on 2023-08-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prueba_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='cantidad',
            field=models.CharField(max_length=10),
        ),
    ]
